### ISSUE TITLE
Reset the button is required. If possible please added that too. Thanks in advance

### ISSUE THREAD

**Issue by rsuman132** [Source-Set-564/SlidingButton#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nuarz71** [comment]
I think **reset button** is not needed right now. If you wanna change state of the `sliding button`,  you can use change state method e.g `slidingButton.changeState(state,animated)`.

Please describe the **issue** you'r open, as I see you'r only using template description.
Thanks in advance, I will close this issue.
