### ISSUE TITLE
Can't sync gradle, I have a waning: Failed to resolve: id.ss564.lib.slidingbutton:slidingbutton:<latest-version>

### ISSUE THREAD

**Issue by JCAK1967** [Source-Set-564/SlidingButton#2]
**Describe the bug**

I'm working with Android Studio Bumblebee 2021.1.1 patch3
Can't sync gradle, I have a waning:

```
Failed to resolve: id.ss564.lib.slidingbutton:slidingbutton:<latest-version>
<a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Affected Modules: <a href="openFile:C:/AndroidStudioProjects/projectname/app/build.gradle">app</a>
```

**To Reproduce**
Just follow the first step https://github.com/Source-Set-564/SlidingButton#gradle
implementation 'id.ss564.lib.slidingbutton:slidingbutton:<latest-version>'

**Comment by nuarz71** [comment]
@JCAK1967 yeah, currently this lib unmaintained, unresolved because `jFrog` is sunsetting. Sorry for inconvenience, i will move to `maven` and re-planning to do it. thank you
